CONSENT_VERSION = "2026-09-13.v4"
CONSENT_ITEMS = [
    "SENSITIVE_HEALTH_COLLECTION",
    "VOICE_FEATURE_EXTRACTION",
    "CALL_RECORDING",
    "REPORT_SHARING_WITH_CHILD",
    "THIRD_PARTY_AI_PROCESSING",
]
